-- Generated by BookOrbit. Applied automatically when KOReader starts, then removed.
return {
    server_url = "https://buks.lol",
    username = "Kindle",
    userkey = "f751f8e54f4c34b398941489c6585a08",
    generated_at = "2026-10-03T23:46:10.964Z",
}
